### ISSUE TITLE
Not playing the mp3 files.

### ISSUE THREAD

**Issue by arneborgan** [BareConductive/random-touch-mp3#1]
Hi. My touch board is not playing the MP3 after uploading the BareConductive/random-touch-mp3 code. It is working with the Touch_MP3 code. I uploaded both the codes from Arduino 1.6.7
Thank you
arne

**Comment by stefandz** [comment]
Hi Arne

Did you make sure to follow the instructions for setting up the folder structure to play files from in the repo's readme.md?

S
