### ISSUE TITLE
Crash/hangup

### ISSUE THREAD

**Issue by arneborgan** [BareConductive/random-touch-mp3#2]
Hi my two boards are crashing/hanging when receiving to much input. I have connected all 12 points on both cards connected to a grid where the two cards have separate strips of triggering systems. I am touching both at the same time and not. Could there there be a interference between the two?
arne

**Comment by stefandz** [comment]
Hi Arne

This sounds like a support request as opposed to a code issue. Please email
info@bareconductive.com with clear, in-focus and well lit images of your
setup, along with a detailed description of what you are trying to achieve.
We will be able to support you better there.

S

**Comment by arneborgan** [comment]
Thank you. Yes I have emailed them with pictures.
a
